In [15]:
cd C:\Users\qpatole\Programming\WingDataFiles\bee\wings\WingIndexFiles

C:\Users\qpatole\Programming\WingDataFiles\bee\wings\WingIndexFiles


In [16]:
# Gula italienska - Apis Mellifera Ligustica
# Gråa krainerbin - Apis Mellifera Canica
# Mörka nordiska bin - Apis Mellifera Mellifera
# Bakfast - Blanding???

def isApisMelliferaMellifera(Ci, Dv):
    if Dv < 0 and Ci < 1.9:
        return 1
    return 0

In [17]:
import os
import json
import numpy as np
import random
cwd = os.path.join("C:\\","Users","qpatole","Programming","WingDataFiles","bee","wings","WingIndexFiles")

def train_test_split_by_category(x, y, test_size=0.2):
    print("x shape " + str(x.shape))
    print("y shape " + str(y.shape))
    
    #Devide by category
    byCategory = []
    train = np.empty([0,3])
    test = np.empty([0,3])
    #print ("Len data       " + str(len(x)))
    for i in range(0,2):
        data = np.column_stack((x,y))
        byCategory.append(data[data[:,2]==i])
        np.random.shuffle(byCategory[i])
        #print ("Len category " + str(i) + " " + str(len(byCategory[i])))
        split_pos = int(len(byCategory[i])*(test_size))
        #print ("Split pos " + str(split_pos))
        train = np.vstack((train, byCategory[i][split_pos:]))
        test = np.vstack((test, byCategory[i][:split_pos]))
            
        #print("Train shape: " + str(train.shape))
        #print("Test shape: " + str(test.shape))
    return (train[:,0:2], train[:,[2]], test[:,0:2], test[:,[2]])    

def load_DvCi_data(path):
    x_train = []
    y_train = []
    for file in os.listdir(path):
        if not ".json" in file:
            continue
        with open(file) as json_file:  
            data = json.load(json_file)
            for wings in data["wings"]:
                #print (wings["image"] + ", Dv: " + str(wings["Dv"]) + ", Ci: " + str(wings["Ci"]) + ", isApisMelliferaMellifera " + str(isApisMelliferaMellifera(wings["Ci"], wings["Dv"])))
                x_train.append([wings["Dv"], wings["Ci"]])
                y_train.append(isApisMelliferaMellifera(wings["Ci"], wings["Dv"]))
    return train_test_split_by_category(np.array(x_train), np.array(y_train))

(x_train, y_train, x_test, y_test) = load_DvCi_data(cwd)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


x shape (986, 2)
y shape (986,)
(789, 2)
(789, 1)
(197, 2)
(197, 1)


In [18]:
from __future__ import absolute_import, division, print_function

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(256,256)),
    keras.layers.Dense(4, activation=tf.nn.relu),
    #keras.layers.Dense(4, activation=tf.nn.relu),
    keras.layers.Dense(2, activation=tf.nn.softmax)
])

In [19]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [20]:
model.fit(x_train, y_train, epochs=500)

Epoch 1/500
789/789 [==============================] - 0s 220us/sample - loss: 3.5080 - acc: 0.0773
Epoch 2/500
789/789 [==============================] - 0s 48us/sample - loss: 3.0247 - acc: 0.0773
Epoch 3/500
789/789 [==============================] - 0s 57us/sample - loss: 2.5942 - acc: 0.0773
Epoch 4/500
789/789 [==============================] - 0s 56us/sample - loss: 2.2187 - acc: 0.0773
Epoch 5/500
789/789 [==============================] - 0s 62us/sample - loss: 1.8945 - acc: 0.0773
Epoch 6/500
789/789 [==============================] - 0s 67us/sample - loss: 1.6171 - acc: 0.0773
Epoch 7/500
789/789 [==============================] - 0s 56us/sample - loss: 1.3848 - acc: 0.0773
Epoch 8/500
789/789 [==============================] - 0s 53us/sample - loss: 1.1882 - acc: 0.0773
Epoch 9/500
789/789 [==============================] - 0s 53us/sample - loss: 1.0241 - acc: 0.1039
Epoch 10/500
789/789 [==============================] - 0s 63us/sample - loss: 0.8865 - acc: 0.1863
Epoch 11

789/789 [==============================] - 0s 60us/sample - loss: 0.0279 - acc: 0.9962
Epoch 84/500
789/789 [==============================] - 0s 80us/sample - loss: 0.0278 - acc: 0.9962
Epoch 85/500
789/789 [==============================] - 0s 63us/sample - loss: 0.0276 - acc: 0.9962
Epoch 86/500
789/789 [==============================] - 0s 53us/sample - loss: 0.0274 - acc: 0.9962
Epoch 87/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0272 - acc: 0.9975
Epoch 88/500
789/789 [==============================] - 0s 54us/sample - loss: 0.0270 - acc: 0.9975
Epoch 89/500
789/789 [==============================] - 0s 53us/sample - loss: 0.0268 - acc: 0.9975
Epoch 90/500
789/789 [==============================] - 0s 56us/sample - loss: 0.0267 - acc: 0.9975
Epoch 91/500
789/789 [==============================] - 0s 54us/sample - loss: 0.0265 - acc: 0.9975
Epoch 92/500
789/789 [==============================] - 0s 57us/sample - loss: 0.0264 - acc: 0.9975
Epoch 93/500


789/789 [==============================] - 0s 56us/sample - loss: 0.0207 - acc: 0.9975
Epoch 165/500
789/789 [==============================] - 0s 53us/sample - loss: 0.0206 - acc: 0.9975
Epoch 166/500
789/789 [==============================] - 0s 65us/sample - loss: 0.0206 - acc: 0.9975
Epoch 167/500
789/789 [==============================] - 0s 51us/sample - loss: 0.0205 - acc: 0.9975
Epoch 168/500
789/789 [==============================] - 0s 61us/sample - loss: 0.0205 - acc: 0.9975
Epoch 169/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0205 - acc: 0.9975
Epoch 170/500
789/789 [==============================] - 0s 53us/sample - loss: 0.0204 - acc: 0.9975
Epoch 171/500
789/789 [==============================] - 0s 53us/sample - loss: 0.0204 - acc: 0.9975
Epoch 172/500
789/789 [==============================] - 0s 54us/sample - loss: 0.0203 - acc: 0.9975
Epoch 173/500
789/789 [==============================] - 0s 65us/sample - loss: 0.0203 - acc: 0.9975
Epoc

789/789 [==============================] - 0s 58us/sample - loss: 0.0180 - acc: 0.9987
Epoch 246/500
789/789 [==============================] - 0s 56us/sample - loss: 0.0179 - acc: 0.9987
Epoch 247/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0179 - acc: 0.9987
Epoch 248/500
789/789 [==============================] - 0s 54us/sample - loss: 0.0179 - acc: 0.9987
Epoch 249/500
789/789 [==============================] - 0s 52us/sample - loss: 0.0178 - acc: 0.9987
Epoch 250/500
789/789 [==============================] - 0s 52us/sample - loss: 0.0178 - acc: 0.9987
Epoch 251/500
789/789 [==============================] - 0s 56us/sample - loss: 0.0178 - acc: 0.9987
Epoch 252/500
789/789 [==============================] - 0s 52us/sample - loss: 0.0177 - acc: 0.9987
Epoch 253/500
789/789 [==============================] - 0s 56us/sample - loss: 0.0177 - acc: 0.9987
Epoch 254/500
789/789 [==============================] - 0s 56us/sample - loss: 0.0177 - acc: 0.9987
Epoc

789/789 [==============================] - 0s 50us/sample - loss: 0.0157 - acc: 0.9987
Epoch 327/500
789/789 [==============================] - 0s 49us/sample - loss: 0.0156 - acc: 0.9987
Epoch 328/500
789/789 [==============================] - 0s 51us/sample - loss: 0.0156 - acc: 0.9987
Epoch 329/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0156 - acc: 0.9987
Epoch 330/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0156 - acc: 0.9987
Epoch 331/500
789/789 [==============================] - 0s 57us/sample - loss: 0.0155 - acc: 0.9987
Epoch 332/500
789/789 [==============================] - 0s 53us/sample - loss: 0.0155 - acc: 0.9987
Epoch 333/500
789/789 [==============================] - 0s 52us/sample - loss: 0.0155 - acc: 0.9987
Epoch 334/500
789/789 [==============================] - 0s 51us/sample - loss: 0.0155 - acc: 0.9987
Epoch 335/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0154 - acc: 0.9987
Epoc

789/789 [==============================] - 0s 53us/sample - loss: 0.0139 - acc: 0.9987
Epoch 408/500
789/789 [==============================] - 0s 66us/sample - loss: 0.0139 - acc: 0.9987
Epoch 409/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0138 - acc: 0.9987
Epoch 410/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0138 - acc: 0.9987
Epoch 411/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0137 - acc: 0.9987
Epoch 412/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0137 - acc: 0.9987
Epoch 413/500
789/789 [==============================] - 0s 61us/sample - loss: 0.0137 - acc: 0.9987
Epoch 414/500
789/789 [==============================] - 0s 53us/sample - loss: 0.0137 - acc: 0.9987
Epoch 415/500
789/789 [==============================] - 0s 59us/sample - loss: 0.0137 - acc: 0.9987
Epoch 416/500
789/789 [==============================] - 0s 59us/sample - loss: 0.0136 - acc: 0.9987
Epoc

789/789 [==============================] - 0s 57us/sample - loss: 0.0123 - acc: 0.9987
Epoch 489/500
789/789 [==============================] - 0s 53us/sample - loss: 0.0123 - acc: 0.9987
Epoch 490/500
789/789 [==============================] - 0s 62us/sample - loss: 0.0123 - acc: 0.9987
Epoch 491/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0123 - acc: 0.9987
Epoch 492/500
789/789 [==============================] - 0s 67us/sample - loss: 0.0123 - acc: 0.9987
Epoch 493/500
789/789 [==============================] - 0s 63us/sample - loss: 0.0122 - acc: 0.9987
Epoch 494/500
789/789 [==============================] - 0s 58us/sample - loss: 0.0122 - acc: 0.9987
Epoch 495/500
789/789 [==============================] - 0s 60us/sample - loss: 0.0122 - acc: 0.9987
Epoch 496/500
789/789 [==============================] - 0s 62us/sample - loss: 0.0122 - acc: 0.9987
Epoch 497/500
789/789 [==============================] - 0s 64us/sample - loss: 0.0122 - acc: 0.9987
Epoc

In [27]:
test_loss, test_acc = model.evaluate(x_test, y_test)

print('Test accuracy:', test_acc)

197/197 [==============================] - 0s 51us/sample - loss: 0.0724 - acc: 0.9848
Test accuracy: 0.98477155


In [28]:
predictions = model.predict(x_train)

In [29]:
predictions[0]

array([1., 0.], dtype=float32)

In [24]:
predictions.shape

(789, 2)

In [25]:
[a for a in predictions if a[0] > 0.1 and a[0] < 0.9]

[array([0.8172847, 0.1827153], dtype=float32),
 array([0.22574924, 0.77425075], dtype=float32)]

In [26]:
print(predictions)

[[1.0000000e+00 0.0000000e+00]
 [1.0000000e+00 3.5167511e-23]
 [1.0000000e+00 0.0000000e+00]
 ...
 [1.2214797e-03 9.9877852e-01]
 [7.5503509e-04 9.9924505e-01]
 [9.9136657e-04 9.9900872e-01]]
